baseURL = "http://example.org/"
languageCode = "en-us"
title = "CCTMC"
theme = "ananke"

[social]
twitter = "GoHugoIO"

[params]
  favicon = ""
  description = "The last theme"
  facebook = ""
  twitter = ""
  linkedin = "https://www.linkedin.com"
  featured_image = "/images/CCTMC01.jpg"

[permalinks]
  posts = "/:year/:month/:title/"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    name = "Meetings"
    url = "/post/meetings"
    weight = -110
  [[menu.main]]
    name = "Images"
    url = "/post/images"
    weight = -100
  [[menu.main]]
    name = "Find us"
    url = "/post/welcome"
    weight = -100

	